language: node_js

matrix:
  include:
    - node_js: 10
    - node_js: 12

cache:
  yarn: true

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn lint
  - yarn test

notifications:
  email: false
  slack:
    secure: lM8m/XIWLCBpYEqPikLAVRNQBUrYWc5/3ATg5p0IZBzTCW5UwpLvkr2lhcdJyOgGlv+b9dOQaOhNgN+9orT0S7oMhuaLiyN3G0Tkqlr0LmGYTXMwTQdcGrUfZtVi2ETcNuUgyEvEt2gTvvKPwQSYUr3L9mkXEzCU3U/Vj7HK3S2FxDcs/oyBIMPOfnEFq0dCmysLsXUegyagfpcqv8qZbaONc+dUclcILe8OnjRjv/ueUds0x9oiSNTPudb7hyE67eUHxDnz5y1Iy3MSeutocCA9sqedSgxKUPJUNzyIxYxpADOe7G/VC3VSjWb70JDCb0yT95Z+xlbWtBYgoAzHfhxn4nsCnCJlpr8aIufcwG1RxbIvtD5OT3LH++h4wTywxeMAG+q28W5VRyRwu3TpCnoD8dP8GsvHcX7uHrAiNyoip9EXrxy1tZ3sZykvkpTHUWOeG1nU3tr1GLwbRk9o/nn/5wwXx1juxcqoO+PEkEhshleoWCJUfqmUfNkrHJO1my26Pnrk/gIlN9DBhhQhObkXyLQxZA2GESmOh40qgmhqJlA1Exx83hQ3aM28dgSNMonjynIWnOrP68tAFLrgDj4pGQe/25PqAyl+ftrQjddF/89ntkjNvItAZDPtNuXUtwmPnyI3WjIU5VDcqJcE/w1GU8jQvH1LvnVLZEzXgn8=
