on: push
name: Run tests
jobs:
  eslint:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: install
        run: yarn install
      - name: test
        run: yarn test
